// Official line colours, read from the VBB "linienfarben" CSV.
//
// Extracted from prepare-data.mjs so the rule below can be tested, and so
// src/line-colors.ts can be regenerated from the CSV alone — the colours do not
// depend on the 600 MB GTFS download the rest of that script needs.
//
// The CSV is ';'-separated and ISO-8859-1 encoded (read it with latin1, or the
// "Fähre" row comes out mangled). Column "Linie" is the line name, column
// "background_Hex" the colour.

/**
 * Rows whose "Linie" is a mode, not a line: the colour to use for any line of
 * that mode which has none of its own. They are kept in the map so the source of
 * every colour stays one file, but the UI reads its product fallbacks from
 * PRODUCT_COLORS in main.ts — no line is ever named "Bus".
 */
export const MODE_ROWS = new Set(['Tram', 'Bus', 'Fähre'])

/**
 * Single-letter rows are DB category codes (P, R, S, T — PlusBus, Regio and so
 * on), not lines. Dropped: no VBB line is named with one letter, so they could
 * only ever match by accident.
 */
const isCategoryCode = name => name.length === 1

/**
 * Parse the CSV into `[name, hex]` pairs, in the order the file lists them.
 *
 * Every row with a usable colour is kept. The old rule kept rail lines only,
 * which is why a bus, a ferry, an RE or an RB used to draw in a fallback colour
 * even though VBB publishes one for it.
 */
export function parseLineColors(csvText) {
  const rows = csvText.split(/\r?\n/).filter(l => l.length > 0).map(l => l.split(';'))
  const header = rows[0] ?? []
  const nameCol = header.indexOf('Linie')
  const hexCol = header.indexOf('background_Hex')
  if (nameCol === -1 || hexCol === -1) throw new Error('linienfarben CSV: missing Linie/background_Hex column')
  const out = []
  for (const row of rows.slice(1)) {
    const name = row[nameCol]?.trim()
    const hex = (row[hexCol] ?? '').trim().toUpperCase()
    if (!name || isCategoryCode(name)) continue
    if (!/^#[0-9A-F]{6}$/.test(hex)) continue
    out.push([name, hex])
  }
  return out
}

/** The generated src/line-colors.ts, given the parsed pairs and the notice. */
export function renderLineColorsTs(entries, attribution) {
  return [
    '// Generated by scripts/prepare-data.mjs from the VBB linienfarben CSV.',
    '// Line name -> official color (CSS hex). Missing lines fall back to product colors in the UI.',
    '// Rows named after a MODE (Tram, Bus, Fähre) are VBB\'s own fallback for that mode.',
    '//',
    `// ${attribution}`,
    `export const lineColors: Record<string, string> = {`,
    ...entries.map(([n, h]) => `  ${JSON.stringify(n)}: '${h}',`),
    `}`
  ].join('\n') + '\n'
}
