// Generated by scripts/prepare-data.mjs from VBB linienfarben CSV.
// Line name -> official color (CSS hex). Missing lines fall back to product colors in the UI.
//
// © VBB Verkehrsverbund Berlin-Brandenburg GmbH, CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/). Source: https://unternehmen.vbb.de/gtfs. MODIFIED: rail modes only, route variants selected and simplified, tracks merged, coordinates rounded. See ATTRIBUTION.md.
export const lineColors: Record<string, string> = {
  "S1": '#DA6BA2',
  "S2": '#007734',
  "S25": '#007734',
  "S26": '#007734',
  "S3": '#0066AD',
  "S41": '#AD5937',
  "S42": '#CB6418',
  "S46": '#CD9C53',
  "S47": '#CD9C53',
  "S5": '#EB7405',
  "S7": '#816DA6',
  "S75": '#816DA6',
  "S8": '#66AA22',
  "S85": '#66AA22',
  "S9": '#992746',
  "U1": '#7DAD4C',
  "U2": '#DA421E',
  "U3": '#16683D',
  "U4": '#F0D722',
  "U5": '#7E5330',
  "U6": '#8C6DAB',
  "U7": '#009BD5',
  "U8": '#224F86',
  "U9": '#F3791D',
  "Tram": '#E2001A',
}
